elasticsearch:
  index: "imageinn"
  url: "https://localhost:9200"
  sniff: false
  health-check: false
  password: "123456"
  username: "elastic"
  api-key: "LVBQYzhvOEJmR2szN29aVWNDVng6V0Q3eDBqMllSanFvZmRzY2tJaFhrUQ"
model-endpoint: "http://localhost:5000/encode"
category-mem-cache-path: "../data/pinterest/categories.txt"